export const projects = [
  {
    title: 'Share Me',
    tech: ['TypeScript', 'Next.js', 'Tailwind', 'tRPC', 'Prisma', 'SQLite'],
    desc: 'ShareMe Social Media Application | Pinterest Clone',
    img: '/project-1.png',
    live: 'https://www.vercel.com',
    github: 'https://www.github.com',
    modalContent:
      'ShareMe is a full stack web applications for uploading and sharing images between users, saving your favourite images and adding comments for different pins.[br]Share Me was built with T3 Stack.',
  },
  {
    title: 'Test Title',
    tech: ['test', 'test', 'test', 'test'],
    desc: 'Just a test for project cardJust a test for project cardJust a test for project card',
    img: 'https://images.unsplash.com/photo-1682686581221-c126206d12f0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    live: 'https://www.vercel.com',
    github: 'https://www.github.com',
    modalContent:
      'WorshipHIM is a chord and lyrics app developed to help ease everyone in their worship to God. So that all may know, from the rising of the sun to its setting, That there is none besides God. He is the Lord and theres no other! Praise Him, Worship Him [br]This is a very fun project that i made using React Native.',
  },
  {
    title: 'Test Title',
    tech: ['test', 'test', 'test', 'test'],
    desc: 'Just a test for project cardJust a test for project cardJust a test for project card',
    img: 'https://images.unsplash.com/photo-1682686581221-c126206d12f0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    live: 'https://www.vercel.com',
    github: 'https://www.github.com',
    modalContent:
      'WorshipHIM is a chord and lyrics app developed to help ease everyone in their worship to God. So that all may know, from the rising of the sun to its setting, That there is none besides God. He is the Lord and theres no other! Praise Him, Worship Him [br]This is a very fun project that i made using React Native.',
  },
  {
    title: 'Test Title',
    tech: ['test', 'test', 'test', 'test'],
    desc: 'Just a test for project cardJust a test for project cardJust a test for project card',
    img: 'https://images.unsplash.com/photo-1682686581221-c126206d12f0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    live: 'https://www.vercel.com',
    github: 'https://www.github.com',
    modalContent:
      'WorshipHIM is a chord and lyrics app developed to help ease everyone in their worship to God. So that all may know, from the rising of the sun to its setting, That there is none besides God. He is the Lord and theres no other! Praise Him, Worship Him [br]This is a very fun project that i made using React Native.',
  },
]

export const stack = [
  'TypeScript',
  'Next.js',
  'Tailwind',
  'SASS',
  'React',
  'Redux',
  'CSS3',
  'PostCSS',
  'HTML5',
  'GraphQL',
  'tRPC',
  'JavaScript',
  'REST',
  'Node.js',
  'Express.js',
  'Nest.js',
  'Prisma',
  'TypeORM',
  'PostgreSQL',
  'MySQL',
  'Redis',
  'SQLite',
  'Apache Kafka',
  'Jest',
  'MongoDB',
  'Mongoose',
  'Docker',
  'Kubernetes',
]

export const tools = [
  'Figma',
  'Git',
  'Vercel',
  'Stripe',
  'Twilio',
  'SendGrid',
  'Clerk',
  'Github',
  'Linux',
  'VSCode',
]

export const exp = [
  {
    name: 'Toptal',
    period: 'Jan 2023 - Present',
    title: 'Software Engineer',
    loc: 'Remotely',
    desc: 'I help build and scale Google Photos. Increased throughput of our primary services by 70%. Migrated backend service from Java to Go. Also helped make it look prettier.',
    tech: [
      'TypeScript',
      'Next.js',
      'Tailwind',
      'SASS',
      'PostCSS',
      'tRPC',
      'GraphQL',
      'Nest.js',
      'TypeORM',
      'Prisma',
      'PostgreSQL',
      'MySQL',
      'Apache Kafka',
      'Redis',
    ],
  },
  {
    name: 'Upwork',
    period: 'Nov 2022 - Present',
    title: 'Software Engineer',
    loc: 'Remotely',
    desc: 'I help build and scale Google Photos. Increased throughput of our primary services by 70%. Migrated backend service from Java to Go. Also helped make it look prettier.',
    tech: [
      'TypeScript',
      'React.js',
      'Redux',
      'Tailwind',
      'GraphQL',
      'Node.js',
      'Express.js',
      'Nest.js',
      'TypeORM',
      'PostgreSQL',
    ],
  },
  {
    name: 'Freelancer',
    period: 'August 2022 - Dec 2022',
    title: 'Full Stack Developer',
    loc: 'Remotely',
    desc: 'I help build and scale Google Photos. Increased throughput of our primary services by 70%. Migrated backend service from Java to Go. Also helped make it look prettier.',
    tech: [
      'JavaScript',
      'React.js',
      'Tailwind',
      'REST',
      'Node.js',
      'Express.js',
      'Mongoose',
      'MongoDB',
    ],
  },
  {
    name: 'Fiverr',
    period: 'April 2022 - August 2022',
    title: 'Front End Developer',
    loc: 'Remotely',
    desc: 'I help build and scale Google Photos. Increased throughput of our primary services by 70%. Migrated backend service from Java to Go. Also helped make it look prettier.',
    tech: ['JavaScript', 'React.js', 'CSS3', 'Bootstrap', 'HTML5'],
  },
]

export const socials = {
  linkedIn: 'https://www.linkedin.com/in/omarr-dev/',
  github: 'https://github.com/omarr-dev',
  twitter: 'https://twitter.com/omarr_dev',
  codePen: 'https://codepen.io/omarr-dev',
  email: 'omarmohamed.private@gmail.com',
}
