import { Poppins } from 'next/font/google'
import '@/styles/globals.scss'

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Omar.dev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="max-w-[100vw] bg-primary text-sm text-typography">
        {children}
      </body>
    </html>
  )
}
